# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - default_assignees:
      - "localheinz"
    default_reviewers:
      - "localheinz"
    directory: "/"
    package_manager: "github_actions"
    update_schedule: "daily"

  - default_assignees:
      - "localheinz"
    default_reviewers:
      - "localheinz"
    directory: "/"
    ignored_updates:
      - match:
          dependency_name: "nikic/php-parser"
      - match:
          dependency_name: "phpstan/phpstan"
      - match:
          dependency_name: "zendframework/zend-servicemanager"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
